CREATE TABLE [dbo].[tblPage53] (
    [DataId]                 INT           IDENTITY (1, 1) NOT NULL,
    [ClampSpeed]             NVARCHAR (50) NULL,
    [ClampPressure]          NVARCHAR (50) NULL,
    [SafetySpeed]            NVARCHAR (50) NULL,
    [SafetyPressure]         NVARCHAR (50) NULL,
    [LockingSpeed]           NVARCHAR (50) NULL,
    [LockingPressure]        NVARCHAR (50) NULL,
    [ClampTonnageSpeed]      NVARCHAR (50) NULL,
    [ClampTonnagePressure]   NVARCHAR (50) NULL,
    [CarriageSpeed]          NVARCHAR (50) NULL,
    [CarriagePressure]       NVARCHAR (50) NULL,
    [PreInjectionSpeed]      NVARCHAR (50) NULL,
    [PreInjectionPressure]   NVARCHAR (50) NULL,
    [IntrugenSpeed]          NVARCHAR (50) NULL,
    [IntrugenPressure]       NVARCHAR (50) NULL,
    [InjectionSpeed]         NVARCHAR (50) NULL,
    [InjectionPressure]      NVARCHAR (50) NULL,
    [RefillSpeed]            NVARCHAR (50) NULL,
    [RefillPressure]         NVARCHAR (50) NULL,
    [SuckbackSpeed]          NVARCHAR (50) NULL,
    [SuckbackPressure]       NVARCHAR (50) NULL,
    [DecompressionSpeed]     NVARCHAR (50) NULL,
    [DecompressionPressure]  NVARCHAR (50) NULL,
    [EjectorSpeed]           NVARCHAR (50) NULL,
    [EjectorPressure]        NVARCHAR (50) NULL,
    [CoresSpeed]             NVARCHAR (50) NULL,
    [CoresPressure]          NVARCHAR (50) NULL,
    [MoldHeightSpeed]        NVARCHAR (50) NULL,
    [MoldHeightPressure]     NVARCHAR (50) NULL,
    [SetClampOpenSpeed]      NVARCHAR (50) NULL,
    [ModeClampOpenPressure]  NVARCHAR (50) NULL,
    [SetClampCloseSpeed]     NVARCHAR (50) NULL,
    [ModeClampClosePressure] NVARCHAR (50) NULL,
    [CreatedOn]              DATETIME      DEFAULT (getdate()) NULL,
    [IsActive]               BIT           DEFAULT ((1)) NULL,
    PRIMARY KEY CLUSTERED ([DataId] ASC)
);

