CREATE TABLE [dbo].[tblPage5] (
    [DataId]             INT          IDENTITY (1, 1) NOT NULL,
    [FlowSlow3]          VARCHAR (10) NULL,
    [FlowSlow2]          VARCHAR (10) NULL,
    [FlowFast]           VARCHAR (10) NULL,
    [FlowSlow1]          VARCHAR (10) NULL,
    [FlowDecomp]         VARCHAR (10) NULL,
    [PressureSlow3]      VARCHAR (10) NULL,
    [PressureSlow2]      VARCHAR (10) NULL,
    [PressureFast]       VARCHAR (10) NULL,
    [PressureSlow1]      VARCHAR (10) NULL,
    [PressureDecomp]     VARCHAR (10) NULL,
    [PositionSlow3]      VARCHAR (10) NULL,
    [PositionSlow2]      VARCHAR (10) NULL,
    [PositionFast]       VARCHAR (10) NULL,
    [PositionSlow1]      VARCHAR (10) NULL,
    [PositionDecomp]     VARCHAR (10) NULL,
    [TimeSlow3]          VARCHAR (10) NULL,
    [TimeSlow2]          VARCHAR (10) NULL,
    [TimeFast]           VARCHAR (10) NULL,
    [TimeSlow1]          VARCHAR (10) NULL,
    [TimeDecomp]         VARCHAR (10) NULL,
    [SpeedSlow3]         VARCHAR (10) NULL,
    [SpeedSlow2]         VARCHAR (10) NULL,
    [SpeedFast]          VARCHAR (10) NULL,
    [SpeedSlow1]         VARCHAR (10) NULL,
    [SpeedDecomp]        VARCHAR (10) NULL,
    [ActStageTimeSlow3]  VARCHAR (10) NULL,
    [ActStageTimeSlow2]  VARCHAR (10) NULL,
    [ActStageTimeFast]   VARCHAR (10) NULL,
    [ActStageTimeSlow1]  VARCHAR (10) NULL,
    [ActStageTimeDecomp] VARCHAR (10) NULL,
    [ClampPosition]      VARCHAR (10) NULL,
    [SetModeFlow]        VARCHAR (10) NULL,
    [SetModePressure]    VARCHAR (10) NULL,
    [CreatedOn]          DATETIME     NULL,
    [IsActive]           BIT          NULL,
    CONSTRAINT [PK_tblPage5] PRIMARY KEY CLUSTERED ([DataId] ASC)
);

