CREATE TABLE [dbo].[tblPage20] (
    [DataId]                    INT           IDENTITY (1, 1) NOT NULL,
    [FlowSlowFwd]               NVARCHAR (50) NULL,
    [FlowFastFwd]               NVARCHAR (50) NULL,
    [FlowFastRet]               NVARCHAR (50) NULL,
    [FlowSlowRet]               NVARCHAR (50) NULL,
    [PressureSlowFwd]           NVARCHAR (50) NULL,
    [PressureFastFwd]           NVARCHAR (50) NULL,
    [PressureFastRet]           NVARCHAR (50) NULL,
    [PressureSlowRet]           NVARCHAR (50) NULL,
    [PositionSlowFwd]           NVARCHAR (50) NULL,
    [PositionFastFwd]           NVARCHAR (50) NULL,
    [PositionFastRet]           NVARCHAR (50) NULL,
    [PositionSlowRet]           NVARCHAR (50) NULL,
    [TimeSlowFwd]               NVARCHAR (50) NULL,
    [TimeFastFwd]               NVARCHAR (50) NULL,
    [TimeFastRet]               NVARCHAR (50) NULL,
    [TimeSlowRet]               NVARCHAR (50) NULL,
    [SpeedSlowFwd]              NVARCHAR (50) NULL,
    [SpeedFastFwd]              NVARCHAR (50) NULL,
    [SpeedFastRet]              NVARCHAR (50) NULL,
    [SpeedSlowRet]              NVARCHAR (50) NULL,
    [PresentOperation]          NVARCHAR (50) NULL,
    [CarriagePosition]          NVARCHAR (50) NULL,
    [CarriageMode]              NVARCHAR (50) NULL,
    [CarriageMove]              NVARCHAR (50) NULL,
    [ForwardDuringInjection]    NVARCHAR (50) NULL,
    [ForwardDuringSuckback]     NVARCHAR (50) NULL,
    [ForwardDuringRefill]       NVARCHAR (50) NULL,
    [CarriageForwardStartDelay] NVARCHAR (50) NULL,
    [CarriageRetractStartDelay] NVARCHAR (50) NULL,
    [CreatedOn]                 DATETIME      DEFAULT (getdate()) NULL,
    [IsActive]                  BIT           DEFAULT ((1)) NULL,
    PRIMARY KEY CLUSTERED ([DataId] ASC)
);

