CREATE TABLE [dbo].[tblPage15] (
    [DataId]                INT           IDENTITY (1, 1) NOT NULL,
    [Mode]                  NVARCHAR (50) NULL,
    [TotalInjTimeSet]       NVARCHAR (50) NULL,
    [Elapsed]               NVARCHAR (50) NULL,
    [Remaining]             NVARCHAR (50) NULL,
    [FlowStage5]            NVARCHAR (50) NULL,
    [FlowStage4]            NVARCHAR (50) NULL,
    [FlowStage3]            NVARCHAR (50) NULL,
    [FlowStage2]            NVARCHAR (50) NULL,
    [FlowStage1]            NVARCHAR (50) NULL,
    [FlowIntrugen]          NVARCHAR (50) NULL,
    [FlowPreInject]         NVARCHAR (50) NULL,
    [PressureStage5]        NVARCHAR (50) NULL,
    [PressureStage4]        NVARCHAR (50) NULL,
    [PressureStage3]        NVARCHAR (50) NULL,
    [PressureStage2]        NVARCHAR (50) NULL,
    [PressureStage1]        NVARCHAR (50) NULL,
    [PressureIntrugen]      NVARCHAR (50) NULL,
    [PressurePreInject]     NVARCHAR (50) NULL,
    [PositionStage5]        NVARCHAR (50) NULL,
    [PositionStage4]        NVARCHAR (50) NULL,
    [PositionStage3]        NVARCHAR (50) NULL,
    [PositionStage2]        NVARCHAR (50) NULL,
    [PositionStage1]        NVARCHAR (50) NULL,
    [PositionIntrugen]      NVARCHAR (50) NULL,
    [PositionPreInject]     NVARCHAR (50) NULL,
    [TimeStage5]            NVARCHAR (50) NULL,
    [TimeStage4]            NVARCHAR (50) NULL,
    [TimeStage3]            NVARCHAR (50) NULL,
    [TimeStage2]            NVARCHAR (50) NULL,
    [TimeStage1]            NVARCHAR (50) NULL,
    [TimeIntrugen]          NVARCHAR (50) NULL,
    [TimePreInject]         NVARCHAR (50) NULL,
    [PumpStage5]            NVARCHAR (50) NULL,
    [PumpStage4]            NVARCHAR (50) NULL,
    [PumpStage3]            NVARCHAR (50) NULL,
    [PumpStage2]            NVARCHAR (50) NULL,
    [PumpStage1]            NVARCHAR (50) NULL,
    [PumpIntrugen]          NVARCHAR (50) NULL,
    [PumpPreInject]         NVARCHAR (50) NULL,
    [SpeedStage5]           NVARCHAR (50) NULL,
    [SpeedStage4]           NVARCHAR (50) NULL,
    [SpeedStage3]           NVARCHAR (50) NULL,
    [SpeedStage2]           NVARCHAR (50) NULL,
    [SpeedStage1]           NVARCHAR (50) NULL,
    [SpeedIntrugen]         NVARCHAR (50) NULL,
    [SpeedPreInject]        NVARCHAR (50) NULL,
    [ActStageTimeStage5]    NVARCHAR (50) NULL,
    [ActStageTimeStage4]    NVARCHAR (50) NULL,
    [ActStageTimeStage3]    NVARCHAR (50) NULL,
    [ActStageTimeStage2]    NVARCHAR (50) NULL,
    [ActStageTimeStage1]    NVARCHAR (50) NULL,
    [ActStageTimeIntrugen]  NVARCHAR (50) NULL,
    [ActStageTimePreInject] NVARCHAR (50) NULL,
    [ScrewPosition]         NVARCHAR (50) NULL,
    [SwitchoverPosition]    NVARCHAR (50) NULL,
    [InjectionBoostStage]   NVARCHAR (50) NULL,
    [Solenoid]              NVARCHAR (50) NULL,
    [InjectionSetTime]      NVARCHAR (50) NULL,
    [CreatedOn]             DATETIME      NULL,
    [IsActive]              BIT           NULL,
    PRIMARY KEY CLUSTERED ([DataId] ASC)
);

