CREATE TABLE [dbo].[tblPage44] (
    [DataId]        INT           IDENTITY (1, 1) NOT NULL,
    [ClampCount]    NVARCHAR (50) NULL,
    [ClampZero]     NVARCHAR (50) NULL,
    [ClampSpan]     NVARCHAR (50) NULL,
    [ClampMM]       NVARCHAR (50) NULL,
    [ScrewCount]    NVARCHAR (50) NULL,
    [ScrewZero]     NVARCHAR (50) NULL,
    [ScrewSpan]     NVARCHAR (50) NULL,
    [ScrewMM]       NVARCHAR (50) NULL,
    [EjectorCount]  NVARCHAR (50) NULL,
    [EjectorZero]   NVARCHAR (50) NULL,
    [EjectorSpan]   NVARCHAR (50) NULL,
    [EjectorMM]     NVARCHAR (50) NULL,
    [CarriageCount] NVARCHAR (50) NULL,
    [CarriageZero]  NVARCHAR (50) NULL,
    [CarriageSpan]  NVARCHAR (50) NULL,
    [CarriageMM]    NVARCHAR (50) NULL,
    [SystemZero]    NVARCHAR (50) NULL,
    [SystemSpan]    NVARCHAR (50) NULL,
    [SystemBar]     NVARCHAR (50) NULL,
    [Zone1Count]    NVARCHAR (50) NULL,
    [Zone1Zero]     NVARCHAR (50) NULL,
    [Zone1Span]     NVARCHAR (50) NULL,
    [Zone1Deg]      NVARCHAR (50) NULL,
    [Zone2Count]    NVARCHAR (50) NULL,
    [Zone2Zero]     NVARCHAR (50) NULL,
    [Zone2Span]     NVARCHAR (50) NULL,
    [Zone2Deg]      NVARCHAR (50) NULL,
    [Zone3Count]    NVARCHAR (50) NULL,
    [Zone3Zero]     NVARCHAR (50) NULL,
    [Zone3Span]     NVARCHAR (50) NULL,
    [Zone3Deg]      NVARCHAR (50) NULL,
    [Zone4Count]    NVARCHAR (50) NULL,
    [Zone4Zero]     NVARCHAR (50) NULL,
    [Zone4Span]     NVARCHAR (50) NULL,
    [Zone4Deg]      NVARCHAR (50) NULL,
    [Zone5Count]    NVARCHAR (50) NULL,
    [Zone5Zero]     NVARCHAR (50) NULL,
    [Zone5Span]     NVARCHAR (50) NULL,
    [Zone5Deg]      NVARCHAR (50) NULL,
    [HydOilCount]   NVARCHAR (50) NULL,
    [HydOilZero]    NVARCHAR (50) NULL,
    [HydOilSpan]    NVARCHAR (50) NULL,
    [HydOilDeg]     NVARCHAR (50) NULL,
    [CreatedOn]     DATETIME      DEFAULT (getdate()) NOT NULL,
    [IsActive]      BIT           DEFAULT ((1)) NOT NULL,
    PRIMARY KEY CLUSTERED ([DataId] ASC)
);

