CREATE TABLE [dbo].[tblPage7] (
    [DataId]                  INT           IDENTITY (1, 1) NOT NULL,
    [EjectorSelection]        NVARCHAR (50) NULL,
    [NoOfRepeatsSet]          NVARCHAR (50) NULL,
    [Executed]                NVARCHAR (50) NULL,
    [PresentStage]            NVARCHAR (50) NULL,
    [EjectorTime]             NVARCHAR (50) NULL,
    [FlowFwd1]                NVARCHAR (50) NULL,
    [FlowFwd2]                NVARCHAR (50) NULL,
    [FlowRet2]                NVARCHAR (50) NULL,
    [FlowRet1]                NVARCHAR (50) NULL,
    [FlowBack]                NVARCHAR (50) NULL,
    [FlowFront]               NVARCHAR (50) NULL,
    [PressureFwd1]            NVARCHAR (50) NULL,
    [PressureFwd2]            NVARCHAR (50) NULL,
    [PressureRet2]            NVARCHAR (50) NULL,
    [PressureRet1]            NVARCHAR (50) NULL,
    [PressureBack]            NVARCHAR (50) NULL,
    [PressureFront]           NVARCHAR (50) NULL,
    [PositionFwd1]            NVARCHAR (50) NULL,
    [PositionFwd2]            NVARCHAR (50) NULL,
    [PositionRet2]            NVARCHAR (50) NULL,
    [PositionRet1]            NVARCHAR (50) NULL,
    [PositionBack]            NVARCHAR (50) NULL,
    [PositionFront]           NVARCHAR (50) NULL,
    [TimeFwd1]                NVARCHAR (50) NULL,
    [TimeFwd2]                NVARCHAR (50) NULL,
    [TimeRet2]                NVARCHAR (50) NULL,
    [TimeRet1]                NVARCHAR (50) NULL,
    [TimeBack]                NVARCHAR (50) NULL,
    [TimeFront]               NVARCHAR (50) NULL,
    [OffDelayFwd1]            NVARCHAR (50) NULL,
    [OffDelayFwd2]            NVARCHAR (50) NULL,
    [OffDelayRet2]            NVARCHAR (50) NULL,
    [OffDelayRet1]            NVARCHAR (50) NULL,
    [OffDelayBack]            NVARCHAR (50) NULL,
    [OffDelayFront]           NVARCHAR (50) NULL,
    [SpeedFwd1]               NVARCHAR (50) NULL,
    [SpeedFwd2]               NVARCHAR (50) NULL,
    [SpeedRet2]               NVARCHAR (50) NULL,
    [SpeedRet1]               NVARCHAR (50) NULL,
    [SpeedBack]               NVARCHAR (50) NULL,
    [SpeedFront]              NVARCHAR (50) NULL,
    [HydEjectPos]             NVARCHAR (50) NULL,
    [EjectorStartPosition]    NVARCHAR (50) NULL,
    [EjectorStartDelay]       NVARCHAR (50) NULL,
    [EjectorRetractSolenoids] NVARCHAR (50) NULL,
    [EjectorRetractLSW10]     NVARCHAR (50) NULL,
    [CreatedOn]               DATETIME      DEFAULT (getdate()) NULL,
    [IsActive]                BIT           NULL,
    PRIMARY KEY CLUSTERED ([DataId] ASC)
);

