CREATE TABLE [dbo].[tblPage14] (
    [DataId]              INT           IDENTITY (1, 1) NOT NULL,
    [AE1Selection]        NVARCHAR (50) NULL,
    [AE1StartPosition]    NVARCHAR (50) NULL,
    [AE1OnDelay]          NVARCHAR (50) NULL,
    [AE1SetStrokes]       NVARCHAR (50) NULL,
    [AE1OnTime]           NVARCHAR (50) NULL,
    [AE1OffTime]          NVARCHAR (50) NULL,
    [AE1DigitalOutput]    NVARCHAR (50) NULL,
    [AE1Operation]        NVARCHAR (50) NULL,
    [AE1ActStageTime]     NVARCHAR (50) NULL,
    [AE1StrokesExecuted]  NVARCHAR (50) NULL,
    [AE1StrokesRemaining] NVARCHAR (50) NULL,
    [AE2Selection]        NVARCHAR (50) NULL,
    [AE2StartPosition]    NVARCHAR (50) NULL,
    [AE2OnDelay]          NVARCHAR (50) NULL,
    [AE2SetStrokes]       NVARCHAR (50) NULL,
    [AE2OnTime]           NVARCHAR (50) NULL,
    [AE2OffTime]          NVARCHAR (50) NULL,
    [AE2DigitalOutput]    NVARCHAR (50) NULL,
    [AE2Operation]        NVARCHAR (50) NULL,
    [AE2ActStageTime]     NVARCHAR (50) NULL,
    [AE2StrokesExecuted]  NVARCHAR (50) NULL,
    [AE2StrokesRemaining] NVARCHAR (50) NULL,
    [CreatedOn]           DATETIME      DEFAULT (getdate()) NULL,
    [IsActive]            BIT           NULL,
    PRIMARY KEY CLUSTERED ([DataId] ASC)
);

