CREATE TABLE [dbo].[tblPage29] (
    [DataId]             INT           IDENTITY (1, 1) NOT NULL,
    [MoldCloseSet]       NVARCHAR (50) NULL,
    [MoldCloseActual]    NVARCHAR (50) NULL,
    [MoldSafetySet]      NVARCHAR (50) NULL,
    [MoldSafetyActual]   NVARCHAR (50) NULL,
    [MoldLockingSet]     NVARCHAR (50) NULL,
    [MoldLockingActual]  NVARCHAR (50) NULL,
    [PreInjectSet]       NVARCHAR (50) NULL,
    [PreInjectActual]    NVARCHAR (50) NULL,
    [IntrugenSet]        NVARCHAR (50) NULL,
    [IntrugenActual]     NVARCHAR (50) NULL,
    [TotInjectSet]       NVARCHAR (50) NULL,
    [TotInjectActual]    NVARCHAR (50) NULL,
    [Inject1Set]         NVARCHAR (50) NULL,
    [Inject1Actual]      NVARCHAR (50) NULL,
    [Inject2Set]         NVARCHAR (50) NULL,
    [Inject2Actual]      NVARCHAR (50) NULL,
    [Inject3Set]         NVARCHAR (50) NULL,
    [Inject3Actual]      NVARCHAR (50) NULL,
    [Inject4Set]         NVARCHAR (50) NULL,
    [Inject4Actual]      NVARCHAR (50) NULL,
    [Inject5Set]         NVARCHAR (50) NULL,
    [Inject5Actual]      NVARCHAR (50) NULL,
    [MoldOpenHoldSet]    NVARCHAR (50) NULL,
    [MoldOpenHoldActual] NVARCHAR (50) NULL,
    [Hold1Set]           NVARCHAR (50) NULL,
    [Hold1Actual]        NVARCHAR (50) NULL,
    [Hold2Set]           NVARCHAR (50) NULL,
    [Hold2Actual]        NVARCHAR (50) NULL,
    [Hold3Set]           NVARCHAR (50) NULL,
    [Hold3Actual]        NVARCHAR (50) NULL,
    [Hold4Set]           NVARCHAR (50) NULL,
    [Hold4Actual]        NVARCHAR (50) NULL,
    [CoolingSet]         NVARCHAR (50) NULL,
    [CoolingActual]      NVARCHAR (50) NULL,
    [Refill1Set]         NVARCHAR (50) NULL,
    [Refill1Actual]      NVARCHAR (50) NULL,
    [Refill2Set]         NVARCHAR (50) NULL,
    [Refill2Actual]      NVARCHAR (50) NULL,
    [Refill3Set]         NVARCHAR (50) NULL,
    [Refill3Actual]      NVARCHAR (50) NULL,
    [PreSuckbackSet]     NVARCHAR (50) NULL,
    [PreSuckbackActual]  NVARCHAR (50) NULL,
    [PostSuckbackSet]    NVARCHAR (50) NULL,
    [PostSuckbackActual] NVARCHAR (50) NULL,
    [InitDecompSet]      NVARCHAR (50) NULL,
    [InitDecompActual]   NVARCHAR (50) NULL,
    [UnitFwd1Set]        NVARCHAR (50) NULL,
    [UnitFwd1Actual]     NVARCHAR (50) NULL,
    [UnitRet1Set]        NVARCHAR (50) NULL,
    [UnitRet1Actual]     NVARCHAR (50) NULL,
    [UnitRet2Set]        NVARCHAR (50) NULL,
    [UnitRet2Actual]     NVARCHAR (50) NULL,
    [FinDecomSet]        NVARCHAR (50) NULL,
    [FinDecomActual]     NVARCHAR (50) NULL,
    [TotCycleSet]        NVARCHAR (50) NULL,
    [TotCycleActual]     NVARCHAR (50) NULL,
    [CreatedOn]          DATETIME      DEFAULT (getdate()) NOT NULL,
    [IsActive]           BIT           DEFAULT ((1)) NOT NULL,
    PRIMARY KEY CLUSTERED ([DataId] ASC)
);

