CREATE TABLE [dbo].[tblPage21] (
    [DataId]           INT           IDENTITY (1, 1) NOT NULL,
    [SetTempZone1]     NVARCHAR (20) NULL,
    [LowAlarmZone1]    NVARCHAR (20) NULL,
    [HighAlarmZone1]   NVARCHAR (20) NULL,
    [DutyZone1]        NVARCHAR (20) NULL,
    [OvershootZone1]   NVARCHAR (20) NULL,
    [StatusZone1]      NVARCHAR (20) NULL,
    [ActualTempZone1]  NVARCHAR (20) NULL,
    [SetTempZone2]     NVARCHAR (20) NULL,
    [LowAlarmZone2]    NVARCHAR (20) NULL,
    [HighAlarmZone2]   NVARCHAR (20) NULL,
    [DutyZone2]        NVARCHAR (20) NULL,
    [OvershootZone2]   NVARCHAR (20) NULL,
    [StatusZone2]      NVARCHAR (20) NULL,
    [ActualTempZone2]  NVARCHAR (20) NULL,
    [SetTempZone3]     NVARCHAR (20) NULL,
    [LowAlarmZone3]    NVARCHAR (20) NULL,
    [HighAlarmZone3]   NVARCHAR (20) NULL,
    [DutyZone3]        NVARCHAR (20) NULL,
    [OvershootZone3]   NVARCHAR (20) NULL,
    [StatusZone3]      NVARCHAR (20) NULL,
    [ActualTempZone3]  NVARCHAR (20) NULL,
    [SetTempZone4]     NVARCHAR (20) NULL,
    [LowAlarmZone4]    NVARCHAR (20) NULL,
    [HighAlarmZone4]   NVARCHAR (20) NULL,
    [DutyZone4]        NVARCHAR (20) NULL,
    [OvershootZone4]   NVARCHAR (20) NULL,
    [StatusZone4]      NVARCHAR (20) NULL,
    [ActualTempZone4]  NVARCHAR (20) NULL,
    [SetTempZone5]     NVARCHAR (20) NULL,
    [LowAlarmZone5]    NVARCHAR (20) NULL,
    [HighAlarmZone5]   NVARCHAR (20) NULL,
    [DutyZone5]        NVARCHAR (20) NULL,
    [OvershootZone5]   NVARCHAR (20) NULL,
    [StatusZone5]      NVARCHAR (20) NULL,
    [ActualTempZone5]  NVARCHAR (20) NULL,
    [SetTempHydOil]    NVARCHAR (20) NULL,
    [LowAlarmHydOil]   NVARCHAR (20) NULL,
    [HighAlarmHydOil]  NVARCHAR (20) NULL,
    [DutyHydOil]       NVARCHAR (20) NULL,
    [OvershootHydOil]  NVARCHAR (20) NULL,
    [StatusHydOil]     NVARCHAR (20) NULL,
    [ActualTempHydOil] NVARCHAR (20) NULL,
    [SetTempNozzle]    NVARCHAR (20) NULL,
    [LowAlarmNozzle]   NVARCHAR (20) NULL,
    [HighAlarmNozzle]  NVARCHAR (20) NULL,
    [DutyNozzle]       NVARCHAR (20) NULL,
    [OvershootNozzle]  NVARCHAR (20) NULL,
    [StatusNozzle]     NVARCHAR (20) NULL,
    [ActualTempNozzle] NVARCHAR (20) NULL,
    [CreatedOn]        DATETIME      NULL,
    [IsActive]         BIT           NULL,
    PRIMARY KEY CLUSTERED ([DataId] ASC)
);

