CREATE TABLE [dbo].[tblPage3] (
    [DataId]               INT            IDENTITY (1, 1) NOT NULL,
    [FlowSlow1]            NVARCHAR (MAX) NULL,
    [FlowFast]             NVARCHAR (MAX) NULL,
    [FlowSlow2]            NVARCHAR (MAX) NULL,
    [FlowSafety]           NVARCHAR (MAX) NULL,
    [FlowLocking]          NVARCHAR (MAX) NULL,
    [PressureSlow1]        NVARCHAR (MAX) NULL,
    [PressureFast]         NVARCHAR (MAX) NULL,
    [PressureSlow2]        NVARCHAR (MAX) NULL,
    [PressureSafety]       NVARCHAR (MAX) NULL,
    [PressureLocking]      NVARCHAR (MAX) NULL,
    [PositionSlow1]        NVARCHAR (MAX) NULL,
    [PositionFast]         NVARCHAR (MAX) NULL,
    [PositionSlow2]        NVARCHAR (MAX) NULL,
    [PositionSafety]       NVARCHAR (MAX) NULL,
    [PositionLocking]      NVARCHAR (MAX) NULL,
    [SpeedSlow1]           NVARCHAR (MAX) NULL,
    [SpeedFast]            NVARCHAR (MAX) NULL,
    [SpeedSlow2]           NVARCHAR (MAX) NULL,
    [SpeedSafety]          NVARCHAR (MAX) NULL,
    [SpeedLocking]         NVARCHAR (MAX) NULL,
    [ActStageTimeSlow1]    NVARCHAR (MAX) NULL,
    [ActStageTimeFast]     NVARCHAR (MAX) NULL,
    [ActStageTimeSlow2]    NVARCHAR (MAX) NULL,
    [ActStageTimeSafety]   NVARCHAR (MAX) NULL,
    [ActStageTimeLocking]  NVARCHAR (MAX) NULL,
    [ActualForce]          NVARCHAR (MAX) NULL,
    [ClampPosition]        NVARCHAR (MAX) NULL,
    [MoldCloseTimeSet]     NVARCHAR (MAX) NULL,
    [MoldCloseTimeActual]  NVARCHAR (MAX) NULL,
    [MoldCloseTimeLast]    NVARCHAR (MAX) NULL,
    [MoldSafetyTimeSet]    NVARCHAR (MAX) NULL,
    [MoldSafetyTimeActual] NVARCHAR (MAX) NULL,
    [MoldSafetyTimeLast]   NVARCHAR (MAX) NULL,
    [LockingTimeSet]       NVARCHAR (MAX) NULL,
    [LockingTimeActual]    NVARCHAR (MAX) NULL,
    [LockingTimeLast]      NVARCHAR (MAX) NULL,
    [SetModeFlow]          NVARCHAR (MAX) NULL,
    [SetModePressure]      NVARCHAR (MAX) NULL,
    [CreatedOn]            DATETIME       NULL,
    [IsActive]             BIT            NOT NULL,
    CONSTRAINT [PK__tblPage3__9D05303D2D193D8A] PRIMARY KEY CLUSTERED ([DataId] ASC)
);

