CREATE TABLE [dbo].[tblPage18] (
    [DataId]                   INT            IDENTITY (1, 1) NOT NULL,
    [Model]                    NVARCHAR (100) NULL,
    [CoolingTimeSet]           NVARCHAR (50)  NULL,
    [Remaining]                NVARCHAR (50)  NULL,
    [SelectionIntrugen]        NVARCHAR (50)  NULL,
    [SelectionPreSuckback]     NVARCHAR (50)  NULL,
    [SelectionRefill1]         NVARCHAR (50)  NULL,
    [SelectionRefill2]         NVARCHAR (50)  NULL,
    [SelectionRefill3]         NVARCHAR (50)  NULL,
    [SelectionPostSuckback]    NVARCHAR (50)  NULL,
    [FlowIntrugen]             NVARCHAR (50)  NULL,
    [FlowPreSuckback]          NVARCHAR (50)  NULL,
    [FlowRefill1]              NVARCHAR (50)  NULL,
    [FlowRefill2]              NVARCHAR (50)  NULL,
    [FlowRefill3]              NVARCHAR (50)  NULL,
    [FlowPostSuckback]         NVARCHAR (50)  NULL,
    [SysPreIntrugen]           NVARCHAR (50)  NULL,
    [SysPrePreSuckback]        NVARCHAR (50)  NULL,
    [SysPreRefill1]            NVARCHAR (50)  NULL,
    [SysPreRefill2]            NVARCHAR (50)  NULL,
    [SysPreRefill3]            NVARCHAR (50)  NULL,
    [SysPrePostSuckback]       NVARCHAR (50)  NULL,
    [BackPreIntrugen]          NVARCHAR (50)  NULL,
    [BackPrePreSuckback]       NVARCHAR (50)  NULL,
    [BackPreRefill1]           NVARCHAR (50)  NULL,
    [BackPreRefill2]           NVARCHAR (50)  NULL,
    [BackPreRefill3]           NVARCHAR (50)  NULL,
    [BackPrePostSuckback]      NVARCHAR (50)  NULL,
    [PositionIntrugen]         NVARCHAR (50)  NULL,
    [PositionPreSuckback]      NVARCHAR (50)  NULL,
    [PositionRefill1]          NVARCHAR (50)  NULL,
    [PositionRefill2]          NVARCHAR (50)  NULL,
    [PositionRefill3]          NVARCHAR (50)  NULL,
    [PositionPostSuckback]     NVARCHAR (50)  NULL,
    [TimeIntrugen]             NVARCHAR (50)  NULL,
    [TimePreSuckback]          NVARCHAR (50)  NULL,
    [TimeRefill1]              NVARCHAR (50)  NULL,
    [TimeRefill2]              NVARCHAR (50)  NULL,
    [TimeRefill3]              NVARCHAR (50)  NULL,
    [TimePostSuckback]         NVARCHAR (50)  NULL,
    [ScrewRPMIntrugen]         NVARCHAR (50)  NULL,
    [ScrewRPMPreSuckback]      NVARCHAR (50)  NULL,
    [ScrewRPMRefill1]          NVARCHAR (50)  NULL,
    [ScrewRPMRefill2]          NVARCHAR (50)  NULL,
    [ScrewRPMRefill3]          NVARCHAR (50)  NULL,
    [ScrewRPMPostSuckback]     NVARCHAR (50)  NULL,
    [SpeedIntrugen]            NVARCHAR (50)  NULL,
    [SpeedPreSuckback]         NVARCHAR (50)  NULL,
    [SpeedRefill1]             NVARCHAR (50)  NULL,
    [SpeedRefill2]             NVARCHAR (50)  NULL,
    [SpeedRefill3]             NVARCHAR (50)  NULL,
    [SpeedPostSuckback]        NVARCHAR (50)  NULL,
    [ActStageTimeIntrugen]     NVARCHAR (50)  NULL,
    [ActStageTimePreSuckback]  NVARCHAR (50)  NULL,
    [ActStageTimeRefill1]      NVARCHAR (50)  NULL,
    [ActStageTimeRefill2]      NVARCHAR (50)  NULL,
    [ActStageTimeRefill3]      NVARCHAR (50)  NULL,
    [ActStageTimePostSuckback] NVARCHAR (50)  NULL,
    [ScrewPosition]            NVARCHAR (50)  NULL,
    [RefillingBoostSelection]  NVARCHAR (50)  NULL,
    [Solenoid]                 NVARCHAR (50)  NULL,
    [CreatedOn]                DATETIME       NULL,
    [IsActive]                 BIT            NULL,
    PRIMARY KEY CLUSTERED ([DataId] ASC)
);

